apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-oauth-demo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-oauth-demo
      app.kubernetes.io/name: node-oauth-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: node-oauth-demo
        app.kubernetes.io/name: node-oauth-demo
    spec:
      containers:
      - image: node-oauth-demo
        imagePullPolicy: IfNotPresent
        name: node-oauth-demo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30