name: create issue branch

on:
  issues:
    types: [ assigned ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        with:
          branchName: 'feature-${issue.number}-${issue.title}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branchName: 'feature-${issue.number}-${issue.title}'
