name: release to harbor

on:
  workflow_dispatch:
    inputs:
      dev_version:
        description: 'the tag of the image to release, like `dev-6-02dbc80`'
        default: ''
        required: true
      prod_version:
        description: 'the tag of the image,src to release, like `2.2.3`'
        default: ''
        required: true
  push:
    tags:
      - '2.*.*'
      - '!v1.*.*'
jobs:
  reTagAndPush:
    runs-on: ubuntu-latest
    steps:
    - run: |
        DEVVERSIONIN=${{ github.event.inputs.dev_version }}
        DEVVERSION=${DEVVERSIONIN:-"v2dev"}
        PRODVERSIONIN=${{ github.event.inputs.prod_version }}
        PRODVERSION=${PRODVERSIONIN:-"${{ github.ref_name}}"}
    - run: echo "${DEVVERSION}"
    - run: echo "${PRODVERSION}"
    - id: get-short-version
      run: |
        sversion="${PRODVERSION}"
        echo "::set-output name=sversion::${sversion: 0 :3}"
    - run: echo "${{steps.get-short-version.outputs.sversion}}"
